TEST_VALUE:
  name: 'dev_cookie'
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a4bfbc8de124900d
  FEISHU_APP_SECRET: EzIxxebekSOXgskzjk5INbTEHxGWXCJ5
APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY